main/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

menu/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
]

pizza/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.index, name='index'),
    path('', include('main.urls')),
    path('menu/', include('menu.urls')),

]

main/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models

class Pizza(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=400)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    vegetarian = models.BooleanField(default=False)
    photo = models.ImageField(upload_to='pizza/photos', blank=True)

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'main/index.html')

# Create your views here.

menu/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .models import Pizza

def index(request):
    pizzas = Pizza.objects.all().order_by('price')
    output = ' , '.join([p.name + " : " + str(p.price) + " $" for p in pizzas])
    # return HttpResponse(f"Les Pizzas : {output}")
    return render(request, 'menu/index.html', {'pizzas': pizzas})

pizza/views.py
from django.http import HttpResponse

def index(request):
    return HttpResponse("Hello, world. You're at the pizza index.")

main/templates/main/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
<div id="logo">
    <img src="{% static 'main/images/main_logo.png' %}" alt="logo"> <!-- Add your logo here -->
    <a href="{% url 'menu:index' %}" target="_blank">Menu</a>

</div>
</body>
</html>

menu/templates/menu/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Menu Pizzas</title>
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
</head>
<body>
<div id="logo">
    <a href="{% url 'main:index' %}" target="_blank"><img src="{% static 'menu/images/small_logo.png' %}" alt="logo"></a>
</div>
<div class="title">
    <h1>Menu Pizzas</h1>
</div>

<div class="menu">
    {% for pizza in pizzas %}
    <div class="menu-item">
        <span class="menu-span">{{ pizza.name }}</span>
        <span class="menu-price">{{ pizza.price | floatformat:2 }}€</span>
        <span class="menu-description">{{ pizza.description }}</span>
        {% if pizza.vegetarian %}
        <span class="badge">Vegetarien</span>
        {% endif %}
    </div>

    {% endfor %}
</div>
</body>
</html>